spring:
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-offset-reset: earliest

app:
  kafka:
    topics:
      company-deletion-requested: company-deletion-requested
      company-deletion-completed: company-deletion-completed

jwt:
  secret: UnikMicroservicesJwtSecretKeyForLab5NeedsAtLeastThirtyTwoBytes
  expiration: 3600000

security:
  whitelist:
    - /auth/**
    - /eureka/**
    - /actuator/**
